apiVersion: v1
kind: ConfigMap
metadata:
  name: meshcentral-new
data:
  MESH_PROTOCOL: "ws"
  MESH_NGINX_HOST: "localhost"
  MESH_EXTERNAL_PORT: "8383"
  MESH_DEVICE_GROUP: "OpenFrame"
  MESH_NGINX_NAT_HOST: ""
  OPENFRAME_MODE: "true"
  OPENFRAME_GATEWAY_URL: ""
