{{- if not .Values.credentials.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: meshcentral-credentials
  labels:
    {{- include "meshcentral.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.credentials.meshUserKey }}: {{ .Values.credentials.meshUserValue | quote }}
  {{ .Values.credentials.meshPassKey }}: {{ .Values.credentials.meshPassValue | quote }}
  {{ .Values.credentials.meshConfigKeyKey }}: {{ .Values.credentials.meshConfigKeyValue | quote }}
{{- end }}

---

apiVersion: v1
kind: Secret
metadata:
  name: meshcentral-config
type: Opaque
stringData:
  config.json: |
    {{- .Values.config | toPrettyJson | nindent 4 }}
