apiVersion: v1
kind: Service
metadata:
  name: meshcentral
spec:
  type: ClusterIP
  selector:
    {{- include "meshcentral.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.config.settings.port | default 4430 }}
      targetPort: http
      protocol: TCP
      name: http
