sequenceDiagram
    participant Client
    participant Server

    Server->>Client: RSA Public Key
    Client->>Client: Verify & Approve Key
    Client->>Server: Client RSA Public Key
    Client->>Server: Encrypted Client Random
    Server->>Client: Encrypted Server Random
    Client->>Client: Derive Session Keys
    Client->>Server: Encrypted Hash
    Server->>Client: Encrypted Hash
    Client->>Server: Encrypted Credentials
