flowchart TD
    Utilities["Xterm Core Utilities Main"] --> RenderService
    Utilities --> BufferService
    Utilities --> MouseService
    Utilities --> ThemeService
    Utilities --> CoreBrowserService
